package com.hyygybs.mobutilities;

import net.minecraftforge.common.ForgeConfigSpec;

public final class MobUtilitiesConfig {
    private static final ForgeConfigSpec.Builder BUILDER = new ForgeConfigSpec.Builder();

    public static final ForgeConfigSpec.IntValue RESOLVER_BASE_TICKS = BUILDER
            .comment("Base ticks required for the resolver to process a mob container.")
            .defineInRange("resolverBaseTicks", 200, 1, Integer.MAX_VALUE);
    public static final ForgeConfigSpec.IntValue GENERATOR_BASE_TICKS = BUILDER
            .comment("Base ticks required for a generator to burn one resource item.")
            .defineInRange("generatorBaseTicks", 100, 1, Integer.MAX_VALUE);
    public static final ForgeConfigSpec.IntValue FARM_BASE_TICKS = BUILDER
            .comment("Base ticks required for the mob farm to simulate one loot roll.")
            .defineInRange("farmBaseTicks", 120, 1, Integer.MAX_VALUE);
    public static final ForgeConfigSpec.IntValue REGENERATOR_BASE_TICKS = BUILDER
            .comment("Base ticks required for the regenerator to create a new mob.")
            .defineInRange("regeneratorBaseTicks", 240, 1, Integer.MAX_VALUE);
    public static final ForgeConfigSpec.IntValue BLOOD_ENERGY_PER_ITEM = BUILDER
            .comment("FE generated by the blood energy generator for one matter item.")
            .defineInRange("bloodEnergyPerItem", 1200, 1, Integer.MAX_VALUE);
    public static final ForgeConfigSpec.IntValue SOUL_ENERGY_PER_ITEM = BUILDER
            .comment("FE generated by the soul energy generator for one spirit item.")
            .defineInRange("soulEnergyPerItem", 1800, 1, Integer.MAX_VALUE);
    public static final ForgeConfigSpec.IntValue FARM_ENERGY_PER_OPERATION = BUILDER
            .comment("FE consumed by the mob farm for one operation.")
            .defineInRange("farmEnergyPerOperation", 300, 0, Integer.MAX_VALUE);
    public static final ForgeConfigSpec.IntValue FARM_EXPERIENCE_PER_OPERATION = BUILDER
            .comment("Experience items consumed by the mob farm for one operation.")
            .defineInRange("farmExperiencePerOperation", 2, 0, Integer.MAX_VALUE);
    public static final ForgeConfigSpec.IntValue REGENERATOR_MATTER_COST = BUILDER
            .comment("Matter items consumed by the regenerator.")
            .defineInRange("regeneratorMatterCost", 6, 1, Integer.MAX_VALUE);
    public static final ForgeConfigSpec.IntValue REGENERATOR_SPIRIT_COST = BUILDER
            .comment("Spirit items consumed by the regenerator.")
            .defineInRange("regeneratorSpiritCost", 4, 1, Integer.MAX_VALUE);
    public static final ForgeConfigSpec.BooleanValue ALLOW_BOSSES = BUILDER
            .comment("Whether the mob container can capture boss mobs.")
            .define("allowBosses", false);

    public static final ForgeConfigSpec SPEC = BUILDER.build();

    private MobUtilitiesConfig() {
    }
}
